### ISSUE TITLE
support question => generating HTML

### ISSUE THREAD

**Issue by ORESoftware** [tjwebb/node-google-discovery-document#1]
Hi there, thanks for this project. I am a bit mystified about how to take the discovery document JSON and turn it into HTML to be viewed by a browser in more human readable form. There must be some tool that can do this that already exists.

I am trying to determine if this project accomplishes this, or if there is some other tool out there that can do this. Hopefully you can help point me in the right direction, thanks!

**Comment by tjwebb** [comment]
It does not produce HTML. It ingests a database schema and produces JSON. Sorry, it sounds like this module won't quite do what you need it to.

**Comment by ORESoftware** [comment]
ok thx, do you happen to have any info regarding tools that turn Google
Discovery API JSON into HTML pages?

I am finding it difficult to find information on this...surely there is
something that does this?

**Comment by tjwebb** [comment]
I don't know of anything, sorry. I built this tool almost 3 years ago, but even then, it was hard to find resources. Google Discovery Documents are pretty archaic at this point. I don't know anyone who uses them any longer. 

Good luck, sorry I can't be of any further help.

**Comment by ORESoftware** [comment]
no prob - thanks anyway! Looks like best bet is to convert to swagger format and use that, but this all seems strange
